package entities;

public class Employee extends User {
  private Long code;
  private String testing;
  /*

  error eto ta mal

   */
//asdkjsakdkad
  public Employee() {
    super();
  }
/*kjhkdasak*/
  public Long getCode() {
    var aJKJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ="holaKAJSDAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAASKLASKJDKASKKKKKKKKKKKKDKJSDJDDDDDDDDDDDDDDDDDDDD";
    return
            code;
  }

  public void setCode(Long code) {
    this.code = code;
  }
}
